version: '3.8'

services:
  riptide-transformation-services:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /etc/ssl/certs/dev-certificate.pem:/etc/ssl/certs/dev-certificate.pem
      - /etc/ssl/certs/dev-private-key.pem:/etc/ssl/certs/dev-private-key.pem


